# mkdocs.yml
site_name: "HAFER ML"
site_author: L Ma
site_description: "HAFER ML"
site_url: "https://emptymalei.github.io/haferml"
repo_url: "https://github.com/emptymalei/haferml"
edit_uri: "blob/gh-pages/docs/"
repo_name: "emptymalei/haferml"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
      watch:
        - haferml


nav:
  - "Home": index.md
  - "Tutorials": tutorials/index.md
  - References:
    - "Data":
      - "Data": references/data/index.md
      - "Analyze":
        - references/data/analyze/index.md
        - "Describe": references/data/analyze/describe.md
      - "Wrangle":
        - references/data/wrangle/index.md
        - "Datetime": references/data/wrangle/datetime.md
        - "JSON": references/data/wrangle/json.md
        - "MISC": references/data/wrangle/misc.md
    - "ETL":
      - "ETL": references/etl/index.md
      - "Extract": references/etl/extract/index.md
      - "Transform":
        - "Transform": references/etl/transform/index.md
        - "Pipeline": references/etl/transform/pipeline.md
    - "Preprocess":
      - "Preprocess": references/preprocess/index.md
      - "Ingredients": references/preprocess/ingredients.md
      - "Pipeline": references/preprocess/pipeline.md
    - "Sync":
      - "Sync": references/sync/index.md
      - "AWS": references/sync/aws.md
      - "Local": references/sync/local.md

