# mkdocs.yml
site_name: "HAFER ML"
site_author: L Ma
site_description: "HAFER ML"
site_url: "https://emptymalei.github.io/haferml"
repo_url: "https://github.com/emptymalei/haferml"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/haferml"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo_badge.svg



markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            docstring_style: "restructured-text"
            members: yes
            filters:
              - "^_[^_]"
      watch:
        - haferml


nav:
  - "Home": index.md
  - "Tutorials":
    - "Tutorials": tutorials/index.md
    - "Data Manipulation":
      - "Introduction": tutorials/data_manipulation/index.md
    - "Building Models":
      - "Introduction": tutorials/build_models/index.md
    - "Perservation":
      - "Introduction": tutorials/preservation/index.md
    - "Rideindego":
      - "Introduction": tutorials/rideindego/index.md
      - "Config": tutorials/rideindego/config.md
      - "Extract": tutorials/rideindego/extract.md
      - "Transform": tutorials/rideindego/transform.md
      - "Preprocessing": tutorials/rideindego/preprocessing.md
      - "Random Forest": tutorials/rideindego/random-forest.md
      - "Prediction": tutorials/rideindego/prediction.md
  - References:
    - "Introduction": references/index.md
    - "Data":
      # - "Data": references/data/index.md
      - "data.wrangle":
        # - "Wrangle": references/data/wrangle/index.md
        - "data.wrangle.datetime": references/data/wrangle/datetime.md
        - "data.wrangle.misc": references/data/wrangle/misc.md
    - "ETL":
      # - "ETL": references/etl/index.md
      - "etl.extract": references/etl/extract/index.md
      - "etl.transform":
        # - "Transform": references/etl/transform/index.md
        - "etl.transform.ingredients": references/etl/transform/ingredients.md
        - "etl.transform.pipeline": references/etl/transform/pipeline.md
    - "Preprocess":
      # - "Preprocess": references/preprocess/index.md
      - "preprocess.ingredients": references/preprocess/ingredients.md
      - "preprocess.pipeline": references/preprocess/pipeline.md
    - "Model":
      # - "Model": references/model/index.md
      - "model.dataset": references/model/dataset.md
      - "model.modelset": references/model/modelset.md
      - "model.workflow": references/model/workflow.md
      - "model.pipeline": references/model/pipeline.md
    - "Sync":
      # - "Sync": references/sync/index.md
      - "sync.aws": references/sync/aws.md
      - "sync.local": references/sync/local.md
    - "Blend":
      # - "Blend": references/blend/index.md
      - "blend.config": references/blend/config.md
    - "Utils":
      # - "Utils": references/utils/index.md
      - "utils.sugar": references/utils/sugar.md
    - "Commandline":
      - "Commandline Tool": references/command/index.md
    - "Lab":
      - "Lab": references/lab/index.md
  - "Changelog": changelog.md
